version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb+srv://drc_user:lO8VN1cTq26iXWKA@cluster0.c0g0s.mongodb.net/drc_database?retryWrites=true&w=majority
      - NODE_ENV=development
      - MONGO_DEBUG=true
      - NODE_HOST=localhost
      - NODE_PORT=3000
