version: '2'

services:
  mongo:
    image: mongo:4.1.8-xenial
    container_name: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

  mongo_seed:
    build: ./mongo
    container_name: mongo-seed
    env_file: .env
    links:
      - mongo
    networks:
      - app-network


  node-api:
    container_name: node-api
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - WAIT_HOST=mongo:27017
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    links:
      - mongo
    networks:
      - app-network
    command: npm run dev


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
